version: '3'


services:

  web:
    image: nginx:1.15.6
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
      # 画面遷移時間問題解消の為のvolume追加  適宜アプリ名を変更 html/〇〇/vendor
      - vendor-volume:/var/www/html/okugai-ad/vendor
      - storage-volume:/var/www/html/okugai-ad/storage
    environment:
      TZ: Asia/Tokyo


  app:
    build: ./docker/php
    volumes:
     - ./src:/var/www/html
     # 画面遷移時間問題解消の為のvolume追加  適宜アプリ名を変更 html/〇〇/vendor
     - vendor-volume:/var/www/html/okugai-ad/vendor
     - storage-volume:/var/www/html/okugai-ad/storage
    depends_on:
      - mysql
    environment:
      TZ: Asia/Tokyo


  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: okugai
      MYSQL_USER: okugai
      MYSQL_PASSWORD: okugai
      MYSQL_ROOT_PASSWORD: okugai
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_USER: okugai
      MYSQL_ROOT_PASSWORD: okugai
      TZ: Asia/Tokyo



volumes:
  mysql-data:

  # 画面遷移時間問題解消の為の名前付きvolume追加
  vendor-volume:
    driver: local
  storage-volume:
    driver: local
